language: python
python:
  - "3.6"
  #- "3.7"
  - "3.8"
  - "3.9"
  -"3.10"

install:
  - pip install pytest-cov
  - pip install -U pip setuptools wheel
  - pip install -r docs/requirements.txt
  - pip install .[dev]

script:
  - pytest --cov=./

jobs:
  include:
    - stage: lint
      name: Code quality checks
      install:
        - pip install pre-commit
      script:
        - pre-commit run --all-files
after_success:
  # code coverage :
  - pip install codecov
  - codecov

deploy:
  provider: pypi
  username: "__token__"
  password: $PYPI_API_TOKEN
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
    branch: master
    python: "3.10"
