language: python
python:
  - "3.6"
  #- "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install pytest-cov
  - python setup.py install

script:
  - pytest --cov=./

jobs:
  include:
    - stage: lint
      name: Code quality checks
      install:
        - pip install pre-commit
      script:
        - pre-commit run --all-files
deploy:
  provider: pypi
  username: <username>
  password: <encrypted password>
  edge: true
after_test:
  - ps: |
      pip install wheel
      python setup.py bdist_wheel
      Get-ChildItem dist\*.whl | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
