language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  
install:
  - pip install pytest-cov
  - python setup.py install

script:
  - pytest --cov=./   
  
after_success:
  # codecoverage for Python 3 only
  - if [[ "$TRAVIS_PYTHON_VERSION" != "2.7" ]]; then
      pip install codecov;
      codecov;
    fi
