#! /usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function
import sys
from pytexit import py2tex

args = sys.argv[1:]
if len(args)>0:
    for e in args:
        py2tex(e)
else:
    print("Use: py2tex 'python formula as string'")

